[package]
name = "bees-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
bees = { path = "../bees" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
